<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                exclude-result-prefixes="xsl plnk xml corecom ehdr aia xp20 ora orcl bpws hwf xref ids" version="2.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources/>
    <oracle-xsl-mapper:mapTargets/>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED DEC 03 17:46:18 IST 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <corecom:Fault>
      <xsl:apply-templates select="*/corecom:EBMHeader"/>
      <corecom:FaultNotification>
        <corecom:ReportingDateTime>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </corecom:ReportingDateTime>
        <corecom:CorrectiveAction/>
        <corecom:FaultMessage>
          <corecom:Code/>
          <corecom:Text/>
          <corecom:Severity/>
          <corecom:Stack/>
        </corecom:FaultMessage>
        <corecom:FaultingService>
          <corecom:ID/>
          <corecom:ImplementationCode/>
          <corecom:InstanceID/>
          <corecom:ExecutionContextID/>
        </corecom:FaultingService>
      </corecom:FaultNotification>
    </corecom:Fault>
  </xsl:template>
  <xsl:template match="corecom:EBMHeader">
    <corecom:EBMReference>
      <xsl:apply-templates select="corecom:EBMID"/>
      <xsl:apply-templates select="corecom:EBMName"/>
      <xsl:apply-templates select="corecom:EBOName"/>
      <xsl:apply-templates select="corecom:VerbCode"/>
      <xsl:apply-templates select="corecom:BusinessScope[corecom:BusinessScopeTypeCode='BusinessProcess']"/>
      <xsl:apply-templates select="corecom:Sender"/>
    </corecom:EBMReference>
  </xsl:template>
  <xsl:template match="corecom:BusinessScope">
    <corecom:BusinessScopeReference>
      <xsl:apply-templates select="corecom:ID"/>
      <xsl:apply-templates select="corecom:InstanceID"/>
      <xsl:apply-templates select="corecom:EnterpriseServiceName"/>
      <xsl:apply-templates select="corecom:EnterpriseServiceOperationName"/>
    </corecom:BusinessScopeReference>
  </xsl:template>
  <xsl:template match="corecom:Sender">
    <corecom:SenderReference>
      <xsl:apply-templates select="corecom:ID"/>
      <xsl:apply-templates select="corecom:SenderMessageID"/>
      <xsl:apply-templates select="corecom:TransactionCode"/>
      <xsl:apply-templates select="corecom:ObjectCrossReference"/>
      <xsl:apply-templates select="corecom:Application"/>
    </corecom:SenderReference>
  </xsl:template>
  <xsl:template match="*">
    <xsl:copy-of select="."/>
  </xsl:template>
</xsl:stylesheet>